2024-10-03 13:44:32,402 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-03 13:44:32,409 - celery.worker.consumer.connection - INFO - Connected to redis://127.0.0.1:6379/1
2024-10-03 13:44:32,410 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-03 13:44:32,413 - celery.worker.consumer.mingle - INFO - mingle: searching for neighbors
2024-10-03 13:44:33,440 - celery.worker.consumer.mingle - INFO - mingle: all alone
2024-10-03 13:44:33,450 - celery.apps.worker - INFO - celery@Poco ready.
2024-10-03 13:44:33,452 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-03 13:44:33,456 - celery.worker.pidbox - INFO - pidbox: Connected to redis://127.0.0.1:6379/1.
2024-10-03 13:46:04,888 - celery.worker.strategy - INFO - Task OAback.celery.debug_task[5cadfaff-2c1d-4da6-a7df-10aaa3e45e4a] received
2024-10-03 13:46:04,889 - celery.redirected - WARNING - Request: <Context: {'lang': 'py', 'task': 'OAback.celery.debug_task', 'id': '5cadfaff-2c1d-4da6-a7df-10aaa3e45e4a', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '5cadfaff-2c1d-4da6-a7df-10aaa3e45e4a', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen18612@Poco', 'ignore_result': True, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}, 'properties': {'correlation_id': '5cadfaff-2c1d-4da6-a7df-10aaa3e45e4a', 'reply_to': '155c6b96-225d-3463-9a4d-3f5adae7f797', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': 'e32e220e-10fe-4c45-99c4-236cf92ebf17'}, 'reply_to': '155c6b96-225d-3463-9a4d-3f5adae7f797', 'correlation_id': '5cadfaff-2c1d-4da6-a7df-10aaa3e45e4a', 'hostname': 'celery@Poco', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': False}, 'args': [], 'kwargs': {}, 'is_eager': False, 'callbacks': None, 'errbacks': None, 'chain': None, 'chord': None, 'called_directly': False, 'headers': None, '_protected': 1}>
2024-10-03 13:46:04,899 - celery.app.trace - INFO - Task OAback.celery.debug_task[5cadfaff-2c1d-4da6-a7df-10aaa3e45e4a] succeeded in 0.01600000000325963s: None
2024-10-03 14:01:03,754 - celery.worker.consumer.consumer - ERROR - Received unregistered task of type 'send_mail_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["anpoco@126.com", "[OA System] \\u8d26\\u53f7\\u6fc0\\u6d3b!", "\\u8bf7\\u70b9\\u51fb\\u94fe\\u63a5\\u6fc0\\u6d3b\\u8d26\\u53f7: http://127.0.0.1:8000/staff/activate?token=9RbXdbi9zOEQDuiKiiSS1+WojQKCwL5Fm3JXSlBw3Eo="], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (281b)

The full contents of the message headers:
{'lang': 'py', 'task': 'send_mail_task', 'id': 'f1c7c2d8-76aa-4024-ba92-e2592af8314d', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f1c7c2d8-76aa-4024-ba92-e2592af8314d', 'parent_id': None, 'argsrepr': "('anpoco@126.com', '[OA System] ’À∫≈º§ªÓ!', '«Îµ„ª˜¡¥Ω”º§ªÓ’À∫≈: http://127.0.0.1:8000/staff/activate?token=9RbXdbi9zOEQDuiKiiSS1+WojQKCwL5Fm3JXSlBw3Eo=')", 'kwargsrepr': '{}', 'origin': 'gen2756@Poco', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 659, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'send_mail_task'
2024-10-03 14:02:17,549 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-03 14:02:17,554 - celery.worker.consumer.connection - INFO - Connected to redis://127.0.0.1:6379/1
2024-10-03 14:02:17,556 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-03 14:02:17,557 - celery.worker.consumer.mingle - INFO - mingle: searching for neighbors
2024-10-03 14:02:18,574 - celery.worker.consumer.mingle - INFO - mingle: all alone
2024-10-03 14:02:18,586 - celery.apps.worker - INFO - celery@Poco ready.
2024-10-03 14:02:18,587 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-03 14:02:18,590 - celery.worker.pidbox - INFO - pidbox: Connected to redis://127.0.0.1:6379/1.
2024-10-03 14:02:51,855 - celery.worker.strategy - INFO - Task send_mail_task[0dd7f3b7-f4b3-4061-af19-6af4c73e781f] received
2024-10-03 14:02:53,189 - celery.app.trace - INFO - Task send_mail_task[0dd7f3b7-f4b3-4061-af19-6af4c73e781f] succeeded in 1.327999999979511s: None
2024-10-03 14:24:32,975 - celery.worker.strategy - INFO - Task send_mail_task[714a7859-e014-4928-9488-6ffa7cdd1e84] received
2024-10-03 14:24:34,311 - celery.app.trace - INFO - Task send_mail_task[714a7859-e014-4928-9488-6ffa7cdd1e84] succeeded in 1.327999999979511s: None
2024-10-03 20:40:50,861 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-03 20:40:50,870 - celery.worker.consumer.connection - INFO - Connected to redis://127.0.0.1:6379/1
2024-10-03 20:40:50,871 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-03 20:40:50,873 - celery.worker.consumer.mingle - INFO - mingle: searching for neighbors
2024-10-03 20:40:51,887 - celery.worker.consumer.mingle - INFO - mingle: all alone
2024-10-03 20:40:51,905 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-03 20:40:51,936 - celery.worker.pidbox - INFO - pidbox: Connected to redis://127.0.0.1:6379/1.
2024-10-03 20:40:51,942 - celery.apps.worker - INFO - celery@Poco ready.
2024-10-03 20:44:57,128 - celery.worker.strategy - INFO - Task send_mail_task[e9a1d178-d2c6-4e49-9bb9-dc50fa3f9739] received
2024-10-03 20:44:59,561 - celery.app.trace - INFO - Task send_mail_task[e9a1d178-d2c6-4e49-9bb9-dc50fa3f9739] succeeded in 2.4369999999762513s: None
2024-10-03 21:13:27,537 - celery.worker.strategy - INFO - Task send_mail_task[28f14f81-a6e8-4640-b5cb-9e2333d733ce] received
2024-10-03 21:13:29,079 - celery.app.trace - INFO - Task send_mail_task[28f14f81-a6e8-4640-b5cb-9e2333d733ce] succeeded in 1.5320000000065193s: None
2024-10-03 23:10:24,752 - celery.worker.consumer.consumer - WARNING - consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 593, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\socket.py", line 115, in readline
    self._read_from_socket()
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\socket.py", line 65, in _read_from_socket
    data = self._sock.recv(socket_read_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\gevent\_socketcommon.py", line 660, in recv
    return self._sock.recv(*args)
           ^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] ‘∂≥Ã÷˜ª˙«ø∆»πÿ±’¡À“ª∏ˆœ÷”–µƒ¡¨Ω”°£

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 340, in start
    blueprint.start(self)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\bootsteps.py", line 116, in start
    step.start(parent)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 746, in start
    c.loop(*c.loop_args())
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\loops.py", line 130, in synloop
    connection.drain_events(timeout=2.0)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\virtual\base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 591, in get
    ret = self.handle_event(fileno, event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 573, in handle_event
    return self.on_readable(fileno), self
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 569, in on_readable
    chan.handlers[type]()
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 918, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 928, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 865, in parse_response
    response = self._execute(conn, try_read)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 841, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\retry.py", line 65, in call_with_retry
    fail(error)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 843, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 830, in _disconnect_raise_connect
    raise error
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 842, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 863, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 601, in read_response
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:6379 : (10054, '‘∂≥Ã÷˜ª˙«ø∆»πÿ±’¡À“ª∏ˆœ÷”–µƒ¡¨Ω”°£', None, 10054, None)
2024-10-03 23:10:26,863 - celery.redirected - WARNING - Traceback (most recent call last):
2024-10-03 23:10:26,864 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 593, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,864 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,865 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,865 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\socket.py", line 115, in readline
    self._read_from_socket()
2024-10-03 23:10:26,865 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\socket.py", line 65, in _read_from_socket
    data = self._sock.recv(socket_read_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,866 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\gevent\_socketcommon.py", line 660, in recv
    return self._sock.recv(*args)
           ^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,866 - celery.redirected - WARNING - ConnectionResetError: [WinError 10054] ‘∂≥Ã÷˜ª˙«ø∆»πÿ±’¡À“ª∏ˆœ÷”–µƒ¡¨Ω”°£
2024-10-03 23:10:26,866 - celery.redirected - WARNING - 
During handling of the above exception, another exception occurred:
2024-10-03 23:10:26,866 - celery.redirected - WARNING - Traceback (most recent call last):
2024-10-03 23:10:26,867 - celery.redirected - WARNING -   File "src\\gevent\\_waiter.py", line 122, in gevent._gevent_c_waiter.Waiter.switch
2024-10-03 23:10:26,867 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\pidbox.py", line 118, in loop
    connection.drain_events(timeout=1.0)
2024-10-03 23:10:26,867 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,867 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\virtual\base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
2024-10-03 23:10:26,867 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 591, in get
    ret = self.handle_event(fileno, event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,868 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 573, in handle_event
    return self.on_readable(fileno), self
           ^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,868 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 569, in on_readable
    chan.handlers[type]()
2024-10-03 23:10:26,868 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 918, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,868 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 928, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,868 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 865, in parse_response
    response = self._execute(conn, try_read)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,868 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 841, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,869 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\retry.py", line 65, in call_with_retry
    fail(error)
2024-10-03 23:10:26,869 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 843, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,869 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 830, in _disconnect_raise_connect
    raise error
2024-10-03 23:10:26,869 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\retry.py", line 62, in call_with_retry
    return do()
           ^^^^
2024-10-03 23:10:26,869 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 842, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,869 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 863, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-03 23:10:26,869 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 601, in read_response
    raise ConnectionError(
2024-10-03 23:10:26,869 - celery.redirected - WARNING - redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:6379 : (10054, '‘∂≥Ã÷˜ª˙«ø∆»πÿ±’¡À“ª∏ˆœ÷”–µƒ¡¨Ω”°£', None, 10054, None)
2024-10-03 23:10:26,869 - celery.redirected - WARNING - 2024-10-03T15:10:26Z
2024-10-03 23:10:26,869 - celery.redirected - WARNING -  
2024-10-03 23:10:26,870 - celery.redirected - WARNING - <built-in method switch of gevent._gevent_c_greenlet_primitives.TrackedRawGreenlet object at 0x000001554628B040> failed with ConnectionError
2024-10-03 23:10:26,871 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:391: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered
back to the queue. You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss
setting. In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

2024-10-03 23:10:26,871 - celery.worker.consumer.consumer - INFO - Temporarily reducing the prefetch count to 4 to avoid over-fetching since 0 tasks are currently being processed.
The prefetch count will be gradually restored to 0 as the tasks complete processing.
2024-10-03 23:10:28,897 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-03 23:10:30,954 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 2.00 seconds... (1/100)

2024-10-03 23:10:35,011 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 4.00 seconds... (2/100)

2024-10-03 23:10:41,070 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 6.00 seconds... (3/100)

2024-10-03 23:10:49,106 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 8.00 seconds... (4/100)

2024-10-03 23:10:59,122 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 10.00 seconds... (5/100)

2024-10-03 23:11:11,152 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 12.00 seconds... (6/100)

2024-10-03 23:11:25,197 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 14.00 seconds... (7/100)

2024-10-03 23:11:41,259 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 16.00 seconds... (8/100)

2024-10-03 23:11:59,279 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 18.00 seconds... (9/100)

2024-10-03 23:12:19,308 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 20.00 seconds... (10/100)

2024-10-03 23:12:41,351 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 22.00 seconds... (11/100)

2024-10-03 23:13:05,422 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 24.00 seconds... (12/100)

2024-10-03 23:13:31,482 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 26.00 seconds... (13/100)

2024-10-03 23:13:59,527 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 28.00 seconds... (14/100)

2024-10-03 23:14:29,581 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 30.00 seconds... (15/100)

2024-10-03 23:15:01,631 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-03 23:15:35,693 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-03 23:16:09,777 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-03 23:16:43,833 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:44:45,035 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:45:19,719 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:45:53,781 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:46:27,838 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:47:01,896 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:47:34,682 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:48:08,752 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:48:42,928 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:49:16,991 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:49:51,064 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:50:25,127 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:50:59,186 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:51:33,248 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:52:07,298 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:52:41,351 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:53:15,398 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:53:49,463 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:54:23,513 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:54:57,565 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:55:31,622 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:56:05,694 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:56:39,745 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:57:13,800 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:57:47,859 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:58:21,905 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:58:55,977 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 12:59:30,022 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:00:04,070 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:00:38,119 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:01:12,174 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:01:46,223 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:02:20,286 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:02:54,357 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:03:28,414 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:04:02,469 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:04:36,494 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:05:10,542 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:05:44,610 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:06:18,658 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:06:52,708 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:07:26,763 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:08:00,819 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:08:34,848 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:09:08,889 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:09:42,944 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:10:17,014 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:10:51,067 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:11:25,171 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:11:59,221 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:12:33,278 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:13:07,331 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:13:41,394 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:14:15,449 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:14:49,523 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:15:23,574 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:15:57,639 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:16:31,704 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:17:05,778 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:17:39,844 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:18:13,920 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:18:47,987 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:19:22,045 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:19:56,101 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:20:30,159 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:21:04,225 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:21:38,292 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:22:12,352 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:22:46,418 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:23:20,476 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:23:54,549 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:24:28,621 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:25:02,704 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:25:36,767 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:26:10,823 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:26:44,889 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:27:18,960 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:27:53,045 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:28:27,104 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:29:01,165 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:29:35,257 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:30:09,326 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-04 13:30:43,417 - celery.worker - CRITICAL - Unrecoverable error: OperationalError('Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£.')
Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\virtual\base.py", line 951, in create_channel
    return self._avail_channels.pop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 358, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 359, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 731, in _connect
    raise err
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 719, in _connect
    sock.connect(socket_address)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\gevent\_socketcommon.py", line 590, in connect
    self._internal_connect(address)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\gevent\_socketcommon.py", line 634, in _internal_connect
    raise _SocketError(err, strerror(err))
ConnectionRefusedError: [Errno 10061] [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 472, in _reraise_as_library_errors
    yield
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 459, in _ensure_connection
    return retry_over_time(
           ^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\utils\functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 934, in _connection_factory
    self._connection = self._establish_connection()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\virtual\base.py", line 975, in establish_connection
    self._avail_channels.append(self.create_channel(self))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\virtual\base.py", line 953, in create_channel
    channel = self.Channel(connection)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 744, in __init__
    self.client.ping()
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\commands\core.py", line 1212, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 1423, in get_connection
    connection.connect()
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 364, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\worker.py", line 202, in start
    self.blueprint.start(self)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\bootsteps.py", line 116, in start
    step.start(parent)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 340, in start
    blueprint.start(self)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\bootsteps.py", line 116, in start
    step.start(parent)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\connection.py", line 21, in start
    c.connection = c.connect()
                   ^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 470, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 476, in connection_for_read
    return self.ensure_connected(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 527, in ensure_connected
    conn = conn.ensure_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 406, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 458, in _ensure_connection
    with ctx():
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£.
2024-10-05 23:28:35,307 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-05 23:28:35,314 - celery.worker.consumer.connection - INFO - Connected to redis://127.0.0.1:6379/1
2024-10-05 23:28:35,314 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-05 23:28:35,317 - celery.worker.consumer.mingle - INFO - mingle: searching for neighbors
2024-10-05 23:28:36,347 - celery.worker.consumer.mingle - INFO - mingle: all alone
2024-10-05 23:28:36,358 - celery.apps.worker - INFO - celery@Poco ready.
2024-10-05 23:28:36,359 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-05 23:28:36,363 - celery.worker.pidbox - INFO - pidbox: Connected to redis://127.0.0.1:6379/1.
2024-10-05 23:29:37,605 - celery.worker.strategy - INFO - Task send_mail_task[97ef6a83-f2f3-4d31-8038-d11d8697efd0] received
2024-10-05 23:29:37,613 - celery.worker.strategy - INFO - Task send_mail_task[69a76408-f086-45ca-8851-540a14373ab2] received
2024-10-05 23:29:37,615 - celery.worker.strategy - INFO - Task send_mail_task[9d0ff293-1bad-419c-b097-27f3590a7752] received
2024-10-05 23:29:39,250 - celery.app.trace - INFO - Task send_mail_task[9d0ff293-1bad-419c-b097-27f3590a7752] succeeded in 1.6410000000614673s: None
2024-10-05 23:29:39,316 - celery.app.trace - INFO - Task send_mail_task[97ef6a83-f2f3-4d31-8038-d11d8697efd0] succeeded in 1.702999999979511s: None
2024-10-05 23:29:39,320 - celery.app.trace - INFO - Task send_mail_task[69a76408-f086-45ca-8851-540a14373ab2] succeeded in 1.702999999979511s: None
2024-10-05 23:35:06,971 - celery.worker.consumer.consumer - WARNING - consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 593, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\socket.py", line 115, in readline
    self._read_from_socket()
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\socket.py", line 65, in _read_from_socket
    data = self._sock.recv(socket_read_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\gevent\_socketcommon.py", line 660, in recv
    return self._sock.recv(*args)
           ^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] ‘∂≥Ã÷˜ª˙«ø∆»πÿ±’¡À“ª∏ˆœ÷”–µƒ¡¨Ω”°£

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 340, in start
    blueprint.start(self)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\bootsteps.py", line 116, in start
    step.start(parent)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 746, in start
    c.loop(*c.loop_args())
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\loops.py", line 130, in synloop
    connection.drain_events(timeout=2.0)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\virtual\base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 591, in get
    ret = self.handle_event(fileno, event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 573, in handle_event
    return self.on_readable(fileno), self
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 569, in on_readable
    chan.handlers[type]()
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 967, in _brpop_read
    dest__item = self.client.parse_response(self.client.connection,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 584, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 601, in read_response
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:6379 : (10054, '‘∂≥Ã÷˜ª˙«ø∆»πÿ±’¡À“ª∏ˆœ÷”–µƒ¡¨Ω”°£', None, 10054, None)
2024-10-05 23:35:09,074 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:391: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered
back to the queue. You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss
setting. In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

2024-10-05 23:35:09,076 - celery.worker.consumer.consumer - INFO - Temporarily reducing the prefetch count to 4 to avoid over-fetching since 0 tasks are currently being processed.
The prefetch count will be gradually restored to 0 as the tasks complete processing.
2024-10-05 23:35:09,112 - celery.redirected - WARNING - Traceback (most recent call last):
2024-10-05 23:35:09,112 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 593, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,113 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,113 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,114 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\socket.py", line 115, in readline
    self._read_from_socket()
2024-10-05 23:35:09,114 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\_parsers\socket.py", line 65, in _read_from_socket
    data = self._sock.recv(socket_read_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,114 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\gevent\_socketcommon.py", line 660, in recv
    return self._sock.recv(*args)
           ^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,114 - celery.redirected - WARNING - ConnectionResetError: [WinError 10054] ‘∂≥Ã÷˜ª˙«ø∆»πÿ±’¡À“ª∏ˆœ÷”–µƒ¡¨Ω”°£
2024-10-05 23:35:09,114 - celery.redirected - WARNING - 
During handling of the above exception, another exception occurred:
2024-10-05 23:35:09,114 - celery.redirected - WARNING - Traceback (most recent call last):
2024-10-05 23:35:09,116 - celery.redirected - WARNING -   File "src\\gevent\\_waiter.py", line 122, in gevent._gevent_c_waiter.Waiter.switch
2024-10-05 23:35:09,116 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\pidbox.py", line 118, in loop
    connection.drain_events(timeout=1.0)
2024-10-05 23:35:09,117 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,118 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\virtual\base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
2024-10-05 23:35:09,119 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 591, in get
    ret = self.handle_event(fileno, event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,120 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 573, in handle_event
    return self.on_readable(fileno), self
           ^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,120 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 569, in on_readable
    chan.handlers[type]()
2024-10-05 23:35:09,121 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 918, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,122 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 928, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,123 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 865, in parse_response
    response = self._execute(conn, try_read)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,123 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 841, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,124 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\retry.py", line 65, in call_with_retry
    fail(error)
2024-10-05 23:35:09,125 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 843, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,126 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 830, in _disconnect_raise_connect
    raise error
2024-10-05 23:35:09,126 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\retry.py", line 62, in call_with_retry
    return do()
           ^^^^
2024-10-05 23:35:09,127 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 842, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,127 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 863, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05 23:35:09,128 - celery.redirected - WARNING -   File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 601, in read_response
    raise ConnectionError(
2024-10-05 23:35:09,128 - celery.redirected - WARNING - redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:6379 : (10054, '‘∂≥Ã÷˜ª˙«ø∆»πÿ±’¡À“ª∏ˆœ÷”–µƒ¡¨Ω”°£', None, 10054, None)
2024-10-05 23:35:09,130 - celery.redirected - WARNING - 2024-10-05T15:35:09Z
2024-10-05 23:35:09,130 - celery.redirected - WARNING -  
2024-10-05 23:35:09,131 - celery.redirected - WARNING - <built-in method switch of gevent._gevent_c_greenlet_primitives.TrackedRawGreenlet object at 0x000001B7FFE84580> failed with ConnectionError
2024-10-05 23:35:11,170 - py.warnings - WARNING - D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

2024-10-05 23:35:13,213 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 2.00 seconds... (1/100)

2024-10-05 23:35:17,277 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 4.00 seconds... (2/100)

2024-10-05 23:35:23,329 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 6.00 seconds... (3/100)

2024-10-05 23:35:31,371 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 8.00 seconds... (4/100)

2024-10-05 23:35:41,419 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 10.00 seconds... (5/100)

2024-10-05 23:35:53,475 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 12.00 seconds... (6/100)

2024-10-05 23:36:07,526 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 14.00 seconds... (7/100)

2024-10-05 23:36:23,591 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 16.00 seconds... (8/100)

2024-10-05 23:36:41,647 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 18.00 seconds... (9/100)

2024-10-05 23:37:01,677 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 20.00 seconds... (10/100)

2024-10-05 23:37:23,719 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 22.00 seconds... (11/100)

2024-10-05 23:37:47,776 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 24.00 seconds... (12/100)

2024-10-05 23:38:13,823 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 26.00 seconds... (13/100)

2024-10-05 23:38:41,867 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 28.00 seconds... (14/100)

2024-10-05 23:39:11,918 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 30.00 seconds... (15/100)

2024-10-05 23:39:43,943 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:40:18,004 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:40:52,061 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:41:26,119 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:42:00,186 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:42:34,235 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:43:08,296 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:43:42,358 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:44:16,429 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:44:50,500 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:45:24,559 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:45:58,610 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:46:32,663 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:47:06,707 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:47:40,758 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:48:14,810 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:48:48,851 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:49:22,926 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:49:56,968 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:50:31,032 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:51:05,101 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:51:39,169 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:52:13,216 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:52:47,275 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:53:21,343 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:53:55,386 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:54:29,447 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:55:03,506 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:55:37,570 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:56:11,635 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:56:45,706 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:57:19,777 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:57:53,843 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:58:27,894 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:59:01,940 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-05 23:59:35,993 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:00:10,045 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:00:44,111 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:01:18,191 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:01:52,244 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:02:26,314 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:03:00,377 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:03:34,439 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:04:08,498 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:04:42,563 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:05:16,631 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:05:50,688 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:06:24,728 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:06:58,791 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:07:32,859 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:08:06,923 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:08:40,983 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:09:15,034 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:09:49,097 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:10:23,153 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:10:57,202 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:11:31,270 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:12:05,344 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:12:39,400 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:13:13,465 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:13:47,512 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:14:21,563 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:14:55,627 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:15:29,695 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:16:03,747 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:16:37,815 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:17:11,866 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:17:45,936 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:18:19,992 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:18:54,055 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:19:28,127 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:20:02,182 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:20:36,223 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:21:10,276 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:21:44,328 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:22:18,398 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:22:52,459 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:23:26,521 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:24:00,581 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:24:34,639 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:25:08,689 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:25:42,735 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:26:16,777 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:26:50,848 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:27:24,923 - celery.worker.consumer.consumer - ERROR - consumer: Cannot connect to redis://127.0.0.1:6379/1: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£..
Trying again in 32.00 seconds... (16/100)

2024-10-06 00:27:58,979 - celery.worker - CRITICAL - Unrecoverable error: OperationalError('Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£.')
Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\virtual\base.py", line 951, in create_channel
    return self._avail_channels.pop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 358, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 359, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 731, in _connect
    raise err
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 719, in _connect
    sock.connect(socket_address)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\gevent\_socketcommon.py", line 590, in connect
    self._internal_connect(address)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\gevent\_socketcommon.py", line 634, in _internal_connect
    raise _SocketError(err, strerror(err))
ConnectionRefusedError: [Errno 10061] [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 472, in _reraise_as_library_errors
    yield
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 459, in _ensure_connection
    return retry_over_time(
           ^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\utils\functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 934, in _connection_factory
    self._connection = self._establish_connection()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\virtual\base.py", line 975, in establish_connection
    self._avail_channels.append(self.create_channel(self))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\virtual\base.py", line 953, in create_channel
    channel = self.Channel(connection)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\transport\redis.py", line 744, in __init__
    self.client.ping()
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\commands\core.py", line 1212, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 1423, in get_connection
    connection.connect()
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\redis\connection.py", line 364, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\worker.py", line 202, in start
    self.blueprint.start(self)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\bootsteps.py", line 116, in start
    step.start(parent)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 340, in start
    blueprint.start(self)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\bootsteps.py", line 116, in start
    step.start(parent)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\connection.py", line 21, in start
    c.connection = c.connect()
                   ^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 470, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 476, in connection_for_read
    return self.ensure_connected(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\celery\worker\consumer\consumer.py", line 527, in ensure_connected
    conn = conn.ensure_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 406, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 458, in _ensure_connection
    with ctx():
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "D:\Develop\Env\miniconda3\envs\dev_env\Lib\site-packages\kombu\connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to 127.0.0.1:6379. [WinError 10061] ”…”⁄ƒø±Íº∆À„ª˙ª˝º´æ‹æ¯£¨Œﬁ∑®¡¨Ω”°£.
